# Generated by Django 4.2.9 on 2024-02-07 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cslug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pslug',
            new_name='slug',
        ),
    ]
