# Generated by Django 4.2.9 on 2024-02-07 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0002_rename_cslug_category_slug_rename_pslug_product_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'product', 'verbose_name_plural': 'productss'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='cdesc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='cimage',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='cname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pavail',
            new_name='avail',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pcategory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pcreated',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pdesc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pimage',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pprice',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pstock',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pupdated',
            new_name='updated',
        ),
    ]
